### ISSUE TITLE
Create checks for illegal moves

### ISSUE THREAD

**Issue by melwil** [oyvindhellenes/proark#5]
Brettet lagres i game state model, illegal moves er definert som en bevegelse til/fra et sett med koordinater i matrisen.

**Comment by oyvindhellenes** [comment]
Well done!

**Comment by melwil** [comment]
Endelig. Den her har plaga meg lenge nå.

**Comment by hajoch** [comment]
Skal ikke gå så langt å si at dette dramatisk vil endre verden til det
bedre, men skal heller ikke se bort fra det.
Takk for all støtten jeg har mottatt under denne lange og krevende
prosessen, det hadde ikke vært mulig å prestere på et så høyt nivå uten
dere og det skal nevnes i talen ved en eventuell Turing-pris. Dere har mitt
ord.

## 

Mvh:
Hallvard Jore Christensen

**Comment by melwil** [comment]
:+1: :hankey:
